name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install and Build
        run: |
          python -V
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          mkdir -p build
          ./build-gh-pages.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: build
